spring.application.name=safeline
server.port=8085

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/safeline
spring.datasource.username=postgres
spring.datasource.password=Tamil
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Security Configuration
spring.security.user.name=admin
spring.security.user.password=admin

# Connection Pooling (HikariCP)
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=1200000

# Multipart Configuration (Fix for 413 Content Too Large)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Debug Logging
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.com.safeline.safeline=DEBUG


 # .\apache-maven-3.9.6\bin\mvn.cmd spring-boot:run
 # .\apache-maven-3.9.6\bin\mvn.cmd spring-boot:run
 # .\apache-maven-3.9.6\bin\mvn.cmd spring-boot:run